sudo: required
services:
  - docker
install:
  - docker build -t test-integration-dockerfile:latest .
  - >
    docker run
    -e "CIRCLE_PROJECT_REPONAME=$(echo $TRAVIS_REPO_SLUG | cut -f2 -d '/')"
    -e "CIRCLE_BUILD_NUM=${TRAVIS_BUILD_NUMBER}"
    -e "IMAGE=${IMAGE:-coreos-beta}"
    -e "CHANNEL=${CHANNEL:-development}"
    -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"                                                                                                                                                                                                    
    -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"                                                                                                                                                                                            
    --name=test-integration-dockerfile-init test-integration-dockerfile:latest /initialize.sh
  - docker commit test-integration-dockerfile-init test-integration-dockerfile:latest
script:
  - docker run --name=test-integration-dockerfile test-integration-dockerfile:latest /run_tests.sh
after_script:
  - docker run --name=DUMP-test-integration-dockerfile test-integration-dockerfile:latest vagrant ssh -- sudo journalctl
  - docker run --name=DESTROY-test-integration-dockerfile test-integration-dockerfile:latest vagrant destroy -f
